# Generated by Django 4.1.7 on 2023-02-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_for', models.CharField(choices=[('ALL', 'ALL'), ('ASHA', 'ASHA'), ('ANM', 'ANM'), ('BENEFICIARY', 'BENEFICIARY')], default='NA', max_length=50)),
                ('language', models.CharField(choices=[('HINDI', 'HINDI'), ('ENGLISH', 'ENGLISH'), ('GUJRATI', 'GUJRATI')], default='NA', max_length=50)),
                ('question_text', models.TextField(default='NA')),
                ('question_code', models.CharField(default='NA', max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WapiGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('HINDI', 'HINDI'), ('ENGLISH', 'ENGLISH'), ('GUJRATI', 'GUJRATI')], default='NA', max_length=50)),
                ('questionNo', models.TextField(default='NA', unique=True)),
                ('questionText', models.TextField(default='NA')),
                ('optionOne', models.CharField(default='NA', max_length=80)),
                ('optionTwo', models.CharField(default='NA', max_length=80)),
                ('optionThree', models.CharField(default='NA', max_length=80)),
                ('optionFour', models.CharField(default='NA', max_length=80)),
                ('rightAnswer', models.CharField(default='NA', max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAPIRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=30)),
                ('reg_mobile', models.CharField(default='NA', max_length=30, unique=True)),
                ('reg_role', models.CharField(default='NA', max_length=30)),
                ('reg_status', models.CharField(default='NA', max_length=30)),
                ('language', models.CharField(default='NA', max_length=30)),
                ('current_stage', models.CharField(default='NA', max_length=30)),
                ('request_for_previous_stage', models.CharField(default='NA', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegANM',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wapi.wapiregistration')),
                ('name', models.CharField(default='NA', max_length=30)),
                ('mobile_number', models.CharField(default='NA', max_length=30, unique=True)),
                ('state', models.CharField(default='NA', max_length=30)),
                ('district', models.CharField(default='NA', max_length=30)),
                ('block', models.CharField(default='NA', max_length=30)),
                ('facility_name', models.CharField(default='NA', max_length=30)),
                ('id_number', models.CharField(default='NA', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegASHA',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wapi.wapiregistration')),
                ('name', models.CharField(default='NA', max_length=30)),
                ('mobile_number', models.CharField(default='NA', max_length=30, unique=True)),
                ('state', models.CharField(default='NA', max_length=30)),
                ('district', models.CharField(default='NA', max_length=30)),
                ('block', models.CharField(default='NA', max_length=30)),
                ('village', models.CharField(default='NA', max_length=30)),
                ('village_population', models.CharField(default='NA', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegBeneficiary',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wapi.wapiregistration')),
                ('rch_number', models.CharField(default='NA', max_length=30)),
                ('name', models.CharField(default='NA', max_length=30)),
                ('mobile_number', models.CharField(default='NA', max_length=30, unique=True)),
                ('age', models.CharField(default='NA', max_length=30)),
                ('state', models.CharField(default='NA', max_length=30)),
                ('district', models.CharField(default='NA', max_length=30)),
                ('block', models.CharField(default='NA', max_length=30)),
                ('village', models.CharField(default='NA', max_length=30)),
                ('user_type', models.CharField(default='NA', max_length=30)),
                ('hb_count', models.CharField(default='NA', max_length=30)),
                ('user_type_status', models.CharField(default='NA', max_length=30)),
                ('health_checkup_status', models.CharField(default='NA', max_length=30)),
                ('ifa_tablet_status', models.CharField(default='NA', max_length=30)),
                ('calcium_tablet_status', models.CharField(default='NA', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WapiGameController',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wapi.wapiregistration')),
                ('level', models.CharField(default='NA', max_length=80)),
                ('total_win', models.CharField(default='NA', max_length=80)),
                ('total_score', models.CharField(default='NA', max_length=80)),
                ('total_rightAnswer', models.CharField(default='NA', max_length=80)),
                ('total_wrongAnswer', models.CharField(default='NA', max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
