# Generated by Django 4.1.7 on 2023-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0002_reganm_estimated_stock_reganm_existing_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reganm',
            name='no_wra_women',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='regasha',
            name='no_wra_women',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
