# Generated by Django 4.1.7 on 2023-03-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0003_reganm_no_wra_women_regasha_no_wra_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAPILanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAPIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(default='NA', max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAPIQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(default='NA', max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAPIRegistrationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resgistration_step', models.CharField(default='NA', max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAPIRoleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='NA', max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAPIValidationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validationname', models.CharField(default='NA', max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAPIQuesManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapi.wapilanguage')),
                ('ques_validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapi.wapivalidationtype')),
                ('questionText', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapi.wapiquestion')),
                ('questionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapi.wapiquestiontype')),
                ('reg_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapi.wapiregistrationstep')),
                ('roleName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapi.wapirolename')),
            ],
            options={
                'unique_together': {('lang', 'roleName', 'reg_step', 'ques_validation', 'questionText', 'questionType')},
            },
        ),
    ]
