# Generated by Django 4.1.7 on 2023-03-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0005_alter_wapilanguage_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wapiquesmanagement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wapiquesmanagement',
            name='answer_text_length',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='wapiquesmanagement',
            unique_together={('lang', 'roleName', 'reg_step', 'ques_validation', 'questionText', 'questionType', 'answer_text_length')},
        ),
    ]
