# Generated by Django 4.1.7 on 2023-03-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0006_alter_wapiquesmanagement_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wapiquesmanagement',
            old_name='questionText',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='wapiquestion',
            old_name='questionText',
            new_name='question',
        ),
        migrations.AddField(
            model_name='wapiquestion',
            name='answer_text_length',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='wapiquestion',
            name='lang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wapi.wapilanguage'),
        ),
        migrations.AddField(
            model_name='wapiquestion',
            name='ques_validation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wapi.wapivalidationtype'),
        ),
        migrations.AddField(
            model_name='wapiquestion',
            name='questionType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wapi.wapiquestiontype'),
        ),
        migrations.AlterUniqueTogether(
            name='wapiquesmanagement',
            unique_together={('lang', 'roleName', 'reg_step', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='wapiquestion',
            unique_together={('lang', 'questionType', 'ques_validation', 'answer_text_length', 'question')},
        ),
        migrations.RemoveField(
            model_name='wapiquesmanagement',
            name='answer_text_length',
        ),
        migrations.RemoveField(
            model_name='wapiquesmanagement',
            name='ques_validation',
        ),
        migrations.RemoveField(
            model_name='wapiquesmanagement',
            name='questionType',
        ),
    ]
