# Generated by Django 4.1.7 on 2023-03-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0007_rename_questiontext_wapiquesmanagement_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wapiquestion',
            name='question',
            field=models.TextField(default='NA', max_length=30, unique=True),
        ),
    ]
