# Generated by Django 4.1.7 on 2023-03-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0008_alter_wapiquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='regbeneficiary',
            name='pragnancy_month',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
