# Generated by Django 4.1.7 on 2023-03-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0011_alter_wapiregistration_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='regasha',
            name='first_trimester',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='regasha',
            name='lakshit_dumpati',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='regasha',
            name='no_cal',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='regasha',
            name='no_folic_acid',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='regasha',
            name='no_ifa',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='regasha',
            name='second_third_trimester',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
