# Generated by Django 4.1.7 on 2023-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0013_reganm_first_trimester_reganm_lakshit_dumpati_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reganm',
            name='annual_lactating_women',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='reganm',
            name='annual_lakshit_women',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='reganm',
            name='annual_pragnant_women',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
