# Generated by Django 4.1.7 on 2023-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0014_reganm_annual_lactating_women_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reganm',
            name='annual_lactating_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='annual_lakshit_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='annual_pragnant_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='block',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='district',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='estimated_stock',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='existing_stock',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='facility_name',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='first_trimester',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='id_number',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='lakshit_dumpati',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='name',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='no_cal',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='no_folic_acid',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='no_ifa',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='no_lactating_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='no_pragnant_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='no_wra_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='second_third_trimester',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reganm',
            name='state',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='block',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='district',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='estimated_stock',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='existing_stock',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='facility_name',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='first_trimester',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='lakshit_dumpati',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='name',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='no_cal',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='no_folic_acid',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='no_ifa',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='no_lactating_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='no_pragnant_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='no_wra_women',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='second_third_trimester',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='state',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='village',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regasha',
            name='village_population',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='age',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='block',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='calcium_tablet_status',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='district',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='hb_count',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='health_checkup_status',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='ifa_tablet_status',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='name',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='pragnancy_month',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='rch_number',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='state',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='user_type',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='user_type_status',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regbeneficiary',
            name='village',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='regquestion',
            name='question_code',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wapigame',
            name='optionFour',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigame',
            name='optionOne',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigame',
            name='optionThree',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigame',
            name='optionTwo',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigame',
            name='questionNo',
            field=models.TextField(default='NA', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wapigame',
            name='questionText',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='wapigame',
            name='rightAnswer',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigamecontroller',
            name='level',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigamecontroller',
            name='total_rightAnswer',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigamecontroller',
            name='total_score',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigamecontroller',
            name='total_win',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapigamecontroller',
            name='total_wrongAnswer',
            field=models.CharField(default='NA', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wapilanguage',
            name='name',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wapiquestion',
            name='answer_text_length',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wapiquestion',
            name='question',
            field=models.TextField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wapiquestiontype',
            name='questionText',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wapiregistration',
            name='current_stage',
            field=models.CharField(default='NA', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='wapiregistration',
            name='language',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wapiregistration',
            name='name',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wapiregistration',
            name='reg_mobile',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wapiregistration',
            name='reg_role',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wapiregistration',
            name='reg_status',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wapiregistration',
            name='request_for_previous_stage',
            field=models.CharField(default='NA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wapiregistrationstep',
            name='resgistration_step',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wapirolename',
            name='role_name',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wapivalidationtype',
            name='validationname',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
    ]
