# Generated by Django 4.1.7 on 2023-03-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0016_remove_reganm_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reganm',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='regasha',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='regbeneficiary',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=30, null=True, unique=True),
        ),
    ]
